// Static imports (you can remove these once fully integrated with Redux)
import f1 from "../assets/f1.png";
import f2 from "../assets/f2.png";
import f3 from "../assets/f3.png";
import f4 from "../assets/f4.png";
import f5 from "../assets/f5.png";


// Fallback data (remove once API is working)
const fallbackCarouselProducts = [
  {
    id: 1,
    name: "DAP",
    price: "1200",
    image: f1,
    inStock: true,
    category: "Fertilizers" as const,
    description: "High quality DAP fertilizer",
  },
  {
    id: 2,
    name: "Urea",
    price: "800",
    image: f4,
    inStock: true,
    category: "Fertilizers" as const,
    description: "Premium Urea fertilizer",
  },
  {
    id: 3,
    name: "Kissan KHAAD",
    price: "300",
    image: f1,
    inStock: false,
    addToCart: true,
    category: "Fertilizers" as const,
    description: "High quality DAP fertilizer",
  },
  {
    id: 4,
    name: "Urea",
    price: "500",
    image: f4,
    inStock: true,
    category: "Fertilizers" as const,
    description: "Premium Urea fertilizer",
  },
  {
    id: 5,
    name: "Beej",
    price: "900",
    image: f5,
    inStock: true,
    category: "Fertilizers" as const,
    description: "Premium Urea fertilizer",
  },
  {
    id: 6,
    name: "Fertilizer Khaad",
    price: "1900",
    image: f2,
    inStock: true,
    category: "Fertilizers" as const,
    description: "Urea fertilizer",
  },
  {
    id: 7,
    name: "Urea",
    price: "1200",
    image: f5,
    inStock: false,
    category: "Fertilizers" as const,
    description: "Premium DAP fertilizer",
  },
];

const fallbackGridProducts = [
  {
    id: 6,
    name: "Nitrophos",
    price: "250",
    image: f1,
    rating: 4,
    reviews: 12,
    category: "Fertilizers" as const,
    description: "Nitrophos fertilizer",
  },
  {
    id: 7,
    name: "Calcium Ammonium",
    price: "1300",
    image: f2,
    rating: 5,
    reviews: 8,
    category: "Fertilizers" as const,
    description: "Calcium Ammonium fertilizer",
  },
  {
    id: 8,
    name: "Nitrophos",
    price: "250",
    image: f3,
    rating: 4,
    reviews: 12,
    category: "Fertilizers" as const,
    description: "Nitrophos fertilizer",
  },
  {
    id: 9,
    name: "Urea",
    price: "1500",
    image: f4,
    rating: 4,
    reviews: 22,
    category: "Fertilizers" as const,
    description: "Premium Urea fertilizer",
  },
  {
    id: 10,
    name: "Calcium Ammonium",
    price: "1300",
    image: f5,
    rating: 5,
    reviews: 8,
    category: "Fertilizers" as const,
    description: "Calcium Ammonium fertilizer",
  },
  {
    id: 11,
    name: "Nitrophos",
    price: "250",
    image: f3,
    rating: 4,
    reviews: 12,
    category: "Pesticides" as const,
    description: "Nitrophos pesticide",
  },
  {
    id: 12,
    name: "Calcium Ammonium",
    price: "1200",
    image: f1,
    rating: 5,
    reviews: 8,
    category: "Pesticides" as const,
    description: "Calcium Ammonium pesticide",
  },
  {
    id: 13,
    name: "Nitrophos",
    price: "250",
    image: f4,
    rating: 4,
    reviews: 12,
    category: "Weed" as const,
    description: "Nitrophos weed control",
  },
  {
    id: 14,
    name: "Urea",
    price: "1500",
    image: f2,
    rating: 4,
    reviews: 11,
    category: "Weed" as const,
    description: "Urea weed control",
  },
  {
    id: 15,
    name: "Calcium Ammonium",
    price: "1300",
    image: f5,
    rating: 5,
    reviews: 8,
    category: "Weed" as const,
    description: "Calcium Ammonium weed control",
  },
];

export { fallbackCarouselProducts, fallbackGridProducts };